# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wei/casper/ZCU111/tenbge_tx_rx/zcu111_tengbe_tx_rx_direct/myproj/myproj.srcs/sources_1/ip/cpu_buffer/cpu_buffer.xci
# IP: The module: 'cpu_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/ZCU111/tenbge_tx_rx/zcu111_tengbe_tx_rx_direct/myproj/myproj.srcs/sources_1/ip/cpu_buffer/cpu_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/wei/casper/ZCU111/tenbge_tx_rx/zcu111_tengbe_tx_rx_direct/myproj/myproj.srcs/sources_1/ip/cpu_buffer/cpu_buffer.xci
# IP: The module: 'cpu_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/ZCU111/tenbge_tx_rx/zcu111_tengbe_tx_rx_direct/myproj/myproj.srcs/sources_1/ip/cpu_buffer/cpu_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
