# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wei/casper/ZCU111/tengbe/zcu111_tengbe/myproj/myproj.srcs/sources_1/ip/arp_cache/arp_cache.xci
# IP: The module: 'arp_cache' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/ZCU111/tengbe/zcu111_tengbe/myproj/myproj.srcs/sources_1/ip/arp_cache/arp_cache_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arp_cache'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/wei/casper/ZCU111/tengbe/zcu111_tengbe/myproj/myproj.srcs/sources_1/ip/arp_cache/arp_cache.xci
# IP: The module: 'arp_cache' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wei/casper/ZCU111/tengbe/zcu111_tengbe/myproj/myproj.srcs/sources_1/ip/arp_cache/arp_cache_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arp_cache'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
